[[file]]
path = ".mydotfiles/com.ml4w.dotfiles.stable/.config/ml4w-dotfiles-settings/com.ml4w.dotfiles/settings.json"
source = "main/dotfiles/.config/ml4w-dotfiles-settings/com.ml4w.dotfiles/settings.json"
backup = true
protect = false

[[file.patch]]
old = '"group":"Waybar"'
new = '"group":"顶栏"'

[[file.patch]]
old = '"group":"Appearance"'
new = '"group":"外观"'

[[file.patch]]
old = '"group":"Default Apps"'
new = '"group":"默认应用"'

[[file.patch]]
old = '"group":"System Settings"'
new = '"group":"系统设置"'

[[file.patch]]
old = '"description":"Configuration of the Waybar status bar."'
new = '"description":"Waybar 状态栏配置。"'

[[file.patch]]
old = '"description":"Change some settings to customize the look and feel."'
new = '"description":"自定义桌面外观和视觉风格。"'

[[file.patch]]
old = '"description":"Please setup your default apps."'
new = '"description":"请配置默认应用。"'

[[file.patch]]
old = '"description":"Overview of core key system settings"'
new = '"description":"核心系统设置概览"'

[[file.patch]]
old = '"Show App Menu"'
new = '"显示应用菜单"'

[[file.patch]]
old = '"Show Taskbar"'
new = '"显示任务栏"'

[[file.patch]]
old = '"Show Quicklinks Menu"'
new = '"显示快捷链接"'

[[file.patch]]
old = '"Show Window Module"'
new = '"显示窗口模块"'

[[file.patch]]
old = '"Show Network Module"'
new = '"显示网络模块"'

[[file.patch]]
old = '"Show Systray Module"'
new = '"显示系统托盘"'

[[file.patch]]
old = '"Rofi Border Size"'
new = '"Rofi 边框大小"'

[[file.patch]]
old = '"Rofi Font"'
new = '"Rofi 字体"'

[[file.patch]]
old = '"Blur Effect"'
new = '"模糊效果"'

[[file.patch]]
old = '"Select Animation"'
new = '"选择动画"'

[[file.patch]]
old = '"Decoration Variants"'
new = '"装饰变体"'

[[file.patch]]
old = '"Window Variants"'
new = '"窗口变体"'

[[file.patch]]
old = '"Workspace Variants"'
new = '"工作区变体"'

[[file.patch]]
old = '"Kitty Cursor Trail"'
new = '"Kitty 光标轨迹"'

[[file.patch]]
old = '"Wallpaper App"'
new = '"壁纸应用"'

[[file.patch]]
old = '"Default Terminal"'
new = '"默认终端"'

[[file.patch]]
old = '"Default Browser"'
new = '"默认浏览器"'

[[file.patch]]
old = '"Default Email Client"'
new = '"默认邮件客户端"'

[[file.patch]]
old = '"Default Filemanager"'
new = '"默认文件管理器"'

[[file.patch]]
old = '"Default Network Manager"'
new = '"默认网络管理器"'

[[file.patch]]
old = '"Default Bluetooth Manager"'
new = '"默认蓝牙管理器"'

[[file.patch]]
old = '"Default Software Manager"'
new = '"默认软件管理器"'

[[file.patch]]
old = '"Default Calculator"'
new = '"默认计算器"'

[[file.patch]]
old = '"Default Screenshot Editor"'
new = '"默认截图编辑器"'

[[file.patch]]
old = '"Default Systemmonitor"'
new = '"默认系统监视器"'

[[file.patch]]
old = '"Default AUR Helper"'
new = '"默认 AUR 助手"'

[[file.patch]]
old = '"Keybinding Variants"'
new = '"快捷键变体"'

[[file.patch]]
old = '"Monitor Variants"'
new = '"显示器变体"'

[[file.patch]]
old = '"Environment Variants"'
new = '"环境变体"'

[[file.patch]]
old = '"Windowrule Variants"'
new = '"窗口规则变体"'

[[file.patch]]
old = '"Launcher"'
new = '"启动器"'
